simv:
	vcs -full64 -cc gcc-4.9 -cpp g++-4.9 \
	sm4_encryptor_wrapper.sv \
	../rtl/sbox.sv \
	../rtl/xor_tree.sv \
	../rtl/key_cache.sv \
	../rtl/roll_shifter.sv \
	../rtl/lru_recorder.sv \
	../rtl/sm4_encryptor.sv \
	../rtl/turn_transform.sv \
	../rtl/priority_encoder.sv 

clean:
	